### PR TITLE
Add support to register grinder recipes in Craft Grid Plus mod.

### PR DESCRIPTION
**Pull request by Skaapdev**
Hi @waxtatect 

This adds support to register grinder recipes in Craft Grid Plus mod.
It relies on my fork of cg plus here:
https://github.com/Skaapdev/cg_plus/commit/a12463ee5250778b1e2d9078db77f050f56f7e12
( I made a [PR](https://github.com/random-geek/cg_plus/pull/6) for cg plus, upstream but project may be abandoned if I look at last activity. )

screenshot_20240404_160922

Thanks!

### CODE REVIEW

**Comment by waxtatect** [comment]
Why not more craft guides
I haven't tested yet, some things to check
Is get_infotext in cg.register_craft_type missing ?
it looks like cg.register_craft  doesn't work with more than one item ? maybe name .. " " .. def[4] ?

**Comment by Skaapdev** [comment]
@waxtatect 

>Is get_infotext in cg.register_craft_type missing ?

yes, but what would you want to put in there? The only thing I seen it used for is fuel burn time and cooking time.
Is there a grinding hardness or something we can use there?

>it looks like cg.register_craft doesn't work with more than one item ? maybe name .. " " .. def[4] ?

No it doesn't right now. I did a basic test and I can add the support so it shows up like this:

screenshot_20240408_215814

That would look much better, give me a bit of time to sort this out.

Thank you!

**Comment by Skaapdev** [comment]
@waxtatect 

I updated the PR.
I found the `def[1]` is actually the power used for a recipe and that is useful thing to have. Especially to compare between grinding diamonds and softer minerals.

screenshot_20240409_084338

Let me know if there is anything else you see.

Thanks!

**Comment by waxtatect** [comment]
There might be one thing, based on your screenshot, select the cotton seed and you get the grinder recipe for flour
It should be the other way around? select the flour and get the grinder recipe to produce it by grinding cotton seed

**Comment by Skaapdev** [comment]
@waxtatect 

Nice catch, the fix is simple and I have updated this PR.
This also lead me to find the issue of overwriting recipes of same name, so I also updated the CGP [PR](https://github.com/random-geek/cg_plus/pull/6)

cotton

wheat

diamond


Thank you!

**Comment by Skaapdev** [comment]
@waxtatect 
Updated to use new implementation provided from https://github.com/random-geek/cg_plus/commit/6511eb8261cb1c292228e76c0906b642e26f2a16

**Comment by Skaapdev** [comment]
@waxtatect 
FYI, I just tested https://github.com/waxtatect/basic_machines/pull/11/commits/737aa60242d3c9f1e909de425a51fa5174fdd020 and it still works. :)

**Pull request merged**
